# TWRP
RECOVERY_VARIANT := twrp
TW_THEME := landscape_hdpi
BOARD_HAS_NO_REAL_SDCARD := true
RECOVERY_SDCARD_ON_DATA := true
RECOVERY_GRAPHICS_USE_LINELENGTH := true
TARGET_RECOVERY_PIXEL_FORMAT := "BGRA_8888"
TW_NO_SCREEN_TIMEOUT := true
TW_NO_USB_STORAGE := true
TW_BRIGHTNESS_PATH := "/brightness"
TW_USE_TOOLBOX := true
